name: medguard
description: Verify medicines with Rwanda FDA
version: 1.0.0+1

environment:
  sdk: ">=3.2.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  http: ^1.2.0
  cupertino_icons: ^1.0.6
  shared_preferences: ^2.2.2
  mobile_scanner: ^4.0.0
  sqflite: ^2.3.0
  path: ^1.8.3
  intl: ^0.20.2
  provider: ^6.1.1
  geolocator: ^10.1.0
  camera: ^0.10.5+5
  url_launcher: ^6.2.2
  share_plus: ^7.2.1
  flutter_email_sender: ^6.0.3
  supabase_flutter: ^2.10.3
  flutter_dotenv: ^6.0.0
  permission_handler: ^11.3.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

dependency_overrides:
  intl: ^0.20.2

flutter:
  uses-material-design: true
  generate: true
  assets:
    - assets/images/
    - .env
